### PR TITLE
Add address_txs RPC

### PR DESCRIPTION
**Pull request by DamjanOstrelic**
Currently gets the tx hash list and has an optional `after_block_height` filter.

But we talked about the possibility of bulk addresses received to this endpoint - I need clarification on that.

If we receive bulk addresses, how is that useful for the user if we are only listing tx hashes? Do we need to return a structure of:

```
[
  address1: { tx_hash1, tx_hash2 },
  address2: { tx_hash1, tx_hash2 }
]
```
in that case?

### CODE REVIEW

**Comment by Scitz0** [comment]
I don't think the address is important in this case. The point is to get all transactions that provided address(es) has a connection to. These can then used on tx_info endpoint to get the details for all returned tx hashes. End-user can then match the address with inputs/outputs of tx as he wants.

**Comment by DamjanOstrelic** [comment]
> I don't think the address is important in this case. The point is to get all transactions that provided address(es) has a connection to. These can then used on tx_info endpoint to get the details for all returned tx hashes. End-user can then match the address with inputs/outputs of tx as he wants.

Okay, in that case, it's simpler and I'll just make it accept a list of addresses.

**Comment by DamjanOstrelic** [comment]
Updated with bulk address input support. Now, the endpoint MUST receive an array of addresses (can still be just 1 or even 0). So some example requests would be:
```
-- without after block filtering:
curl -X POST http://127.0.0.1:8050/rpc/address_txs \
-H 'Content-Type: application/json' \
-d '{
"_payment_address_arr": ["addr1qxqzp46gah6tud2lpqswexleyf78mehpp2r6pl9sr34m2zyz4jgk36t20j5hw2a30r7gv0yfvy3vxt7hv9mt9fn8xxkqh708ww", "addr1q8ytda2q4hdjfsf5frkgpp0knwpnhwdndlcp65an9mjw8u0wjefzrj8h5ezugv59k5fq6rca9mnlqczshny3dpkwdn5q5c0yv4"]
}' \
2>/dev/null | jq .
[
  {
    "tx_hash": "15cc6a1b58309ccd4f762976a1ec6aa0f914c936a87c0e782656a5208c3c0b9f"
  },
  {
    "tx_hash": "28b5527f5cad3caab994fda2bff51c2afffac2ed8b8ed442fbe7cf64bf6e6856"
  },
  {
    "tx_hash": "e01af28b007796b63ed3be4cfd128f7ee309583a3204c1ef95c471c4a4c683ed"
  }
]
```
```
-- with after block filtering:
curl -X POST http://127.0.0.1:8050/rpc/address_txs \
-H 'Content-Type: application/json' \
-d '{
"_payment_address_arr": ["addr1qxqzp46gah6tud2lpqswexleyf78mehpp2r6pl9sr34m2zyz4jgk36t20j5hw2a30r7gv0yfvy3vxt7hv9mt9fn8xxkqh708ww", "addr1q8ytda2q4hdjfsf5frkgpp0knwpnhwdndlcp65an9mjw8u0wjefzrj8h5ezugv59k5fq6rca9mnlqczshny3dpkwdn5q5c0yv4"],
"_after_block_height": 6331086
}' \
2>/dev/null | jq .
[
  {
    "tx_hash": "28b5527f5cad3caab994fda2bff51c2afffac2ed8b8ed442fbe7cf64bf6e6856"
  },
  {
    "tx_hash": "e01af28b007796b63ed3be4cfd128f7ee309583a3204c1ef95c471c4a4c683ed"
  }
]
```

```
-- with one address:
curl -X POST http://127.0.0.1:8050/rpc/address_txs \
-H 'Content-Type: application/json' \
-d '{
"_payment_address_arr": ["addr1qxqzp46gah6tud2lpqswexleyf78mehpp2r6pl9sr34m2zyz4jgk36t20j5hw2a30r7gv0yfvy3vxt7hv9mt9fn8xxkqh708ww"]
}' \
2>/dev/null | jq .
[
  {
    "tx_hash": "15cc6a1b58309ccd4f762976a1ec6aa0f914c936a87c0e782656a5208c3c0b9f"
  },
  {
    "tx_hash": "28b5527f5cad3caab994fda2bff51c2afffac2ed8b8ed442fbe7cf64bf6e6856"
  }
]
```
```
-- with one address and block filter:
curl -X POST http://127.0.0.1:8050/rpc/address_txs \
-H 'Content-Type: application/json' \
-d '{
"_payment_address_arr": ["addr1qxqzp46gah6tud2lpqswexleyf78mehpp2r6pl9sr34m2zyz4jgk36t20j5hw2a30r7gv0yfvy3vxt7hv9mt9fn8xxkqh708ww"],
"_after_block_height": 6331086
}' \
2>/dev/null | jq .
[
  {
    "tx_hash": "28b5527f5cad3caab994fda2bff51c2afffac2ed8b8ed442fbe7cf64bf6e6856"
  }
]
```

The not so great thing about it is that you have to send an array of addresses even if it's just a single address you're interested in. This can be avoided by defining the function using `VARIADIC` argument for the payment address array, but `VARIADIC` arguments must come last in the function definition, meaning that the `_after_block_height` would have to come first, and would have to be specified on every request even when filtering is not wanted.
So I am in favour of having it the way it is now, that the user must send an array of values, but can leave out the optional filter.

**Comment by Scitz0** [comment]
> The not so great thing about it is that you have to send an array of addresses even if it's just a single address you're interested in. This can be avoided by defining the function using `VARIADIC` argument for the payment address array, but `VARIADIC` arguments must come last in the function definition, meaning that the `_after_block_height` would have to come first, and would have to be specified on every request even when filtering is not wanted.
> So I am in favour of having it the way it is now, that the user must send an array of values, but can leave out the optional filter.

I think this is fine as well, even for a single address.

**Comment by rdlrt** [comment]
agree

**Review by rdlrt — APPROVED** [review]

**Comment by rdlrt** [comment]
A small thing, can we use `_payment_addresses` instead of `_payment_address_arr` ?

**Pull request merged**
