### PR TITLE
Env patch

### PR DESCRIPTION
**Pull request by rdlrt**
- env: If using defaults, allow automatic detection of vars. Simplify customisations for users when changing env file
- prereqs: Add dialog to prereqs.sh, required by cntools 6.0.0
- prereqs: Backup env file before overwriting
- gLiveView 1.7

### CODE REVIEW

**Review by Scitz0 — APPROVED** [review]
LGTM

**Comment by Scitz0** [comment]
Merge to be synced with #511

**Comment by Scitz0** [comment]
Sync with #471 and #511 PR to have common variables in env file

**Review by redoracle — APPROVED** [review]
Lgtm

**Comment by rdlrt** [comment]
Superceded by #514

**Pull request closed without merging**
