### PR TITLE
Account addresses rpc

### PR DESCRIPTION
**Pull request by DamjanOstrelic**
1) Do we want to include UTXO values for each individual address here?
2) Do we want to include the `stake_address` with which all of these addresses are associated to?

### CODE REVIEW

**Comment by Scitz0** [comment]
> 1. Do we want to include UTXO values for each individual address here?
I think the flow goes like this to paint a complete picture of an account:
1) Find all addresses used that belong to this account
2) Find all transactions that have a connection to any of these addresses
3) Get all utxo's for the above transactions.
4) Get details for each utxo, e.g. inputs and outputs, each with an array of assets/amount. 
But these would be separate queries in my mind. 

With this said, It might also be interesting to be able to get active unspent utxo's that belong to any of these addresses. Query 4 from above could then be used to get further details about the utxo.  

> 2. Do we want to include the `stake_address` with which all of these addresses are associated to?
I dont think thats necessary, would just result in the same stake address for each row in the table. We could have a separate query that returns the stake address given a base address.

**Comment by DamjanOstrelic** [comment]
> I dont think thats necessary, would just result in the same stake address for each row in the table. We could have a separate query that returns the stake address given a base address. Basically a small part of this query.

Yea, you're right. I was still thinking we could return a JSON, but we switched to returning tables 😄

**Comment by DamjanOstrelic** [comment]
> I think the flow goes like this to paint a complete picture of an account:
> 
> 1. Find all addresses used that belong to this account
> 2. Find all transactions that have a connection to any of these addresses
> 3. Get all utxo's for the above transactions.
> 4. Get details for each utxo, e.g. inputs and outputs, each with an array of assets/amount.
>    But these would be separate queries in my mind.
> 
> With this said, It might also be interesting to be able to get active unspent utxo's that belong to any of these addresses. Query 4 from above could then be used to get further details about the utxo.

I guess somewhere between points 2. and 4., or as point 5. would be to find all historical transactions with their inputs/outputs as well to get a complete picture of an account.

So for this query, are you saying what is there is enough (i.e. completes step 1)?

**Review by rdlrt — APPROVED** [review]
Agree with Ola for scope of this PR and the flow (as some of the items in that flow are already underway on seperate PR)

**Pull request merged**
