### PR TITLE
CNTools 10.2.3

### LINKED ISSUE #1634: [CNTools] - Ledger withdrawal error
**Describe the bug**

When we try to withdraw rewards from the Ledger wallet, we get an error

```
INFO: follow directions on hardware device to witness the transaction
Error: The requested operation failed. Check that your Ledger device is connected, unlocked and with Cardano app running.
Details: Error: Missing signing file for certificate

ERROR: during hardware wallet signing !!
```

**To Reproduce**
1. On the online environment run cntools.sh, go to Funds -> Withdraw Rewards -> Hybrid
2. Select Ledger wallet to withdraw funds
3. Copy offline transaction file to the local environment
4. On the offline environment run cntools.sh, go to Transaction -> Sign, and try to sign the tx
5. See error

**Additional context**

This is happening because with cntools we make a witness for each payment and stake key separately. For some unknown reason this doesn't work properly with the rewards withdrawal transaction. For such transactions we must use the following syntax:

```
cardano-hw-cli transaction witness \
--tx-file tx.transformed \
--hw-signing-file payment.hwsfile \
--hw-signing-file stake.hwsfile \
--mainnet \
--out-file payment.witness \
--out-file stake.witness
```

i.e. use both payment and stake keys at the same time.

P.S. since it's possible this is cardano-hw-cli bug-not-feature, just in case I also opened the issue in the cardano-hw-cli repo https://github.com/vacuumlabs/cardano-hw-cli/issues/162

### PR DESCRIPTION
**Pull request by Scitz0**
## Description
When adding multiple HW signing keys in the same command, you need equally many output witness files. 

## Which issue it fixes?
closes #1634

## How has this been tested?
Yes

### CODE REVIEW

**Comment by TrevorBenson** [comment]
@Scitz0 This is the error I get when using `cntools.sh -b cntools-10.2.3` for registering a Trezor wallet:

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 >> WALLET >> REGISTER
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Online mode  -  The default mode to use if all keys are available

Hybrid mode  -  1) Go through steps to build a transaction file
                2) Copy built tx file to offline computer
                3) Sign it using 'Sign Tx' with keys on offline computer
                   (CNTools started in offline mode '-o' without node connection)
                4) Copy the signed tx file back to online computer and submit using 'Submit Tx'

Selected value: [o] Online

# Select wallet to register (only non-registered wallets shown)
Selected wallet: TrezorWallet-extra2 (Funds: 100.000000 Ada)


INFO: follow directions on hardware device to witness the transaction
Warning! A superfluous HW signing file specified (1 of 2), the witness was not created.
Writing to file '/tmp/cnode/cntools/tx.witness_ly3XH3Q1Me'.
Warning! A superfluous output file specified (2 of 2), the file was not written to.
Command failed: transaction sign-witness  Error: Failed to decode neither the cli's serialisation format nor the ledger's CDDL serialisation format. TextEnvelope error: /tmp/cnode/cntools/tx.witness_OnEKXZHZY9: TextEnvelope aeson decode error: Error in $: not enough input
TextEnvelopeCddl error: /tmp/cnode/cntools/tx.witness_OnEKXZHZY9: Could not JSON decode TextEnvelopeCddl file at: /tmp/cnode/cntools/tx.witness_OnEKXZHZY9 Error: Error in $: not enough input

press any key to proceed ..
```

**Comment by TrevorBenson** [comment]
@Scitz0 
I found the following release notes [Cardano HW CLI v1.10.0 release notes](https://github.com/vacuumlabs/cardano-hw-cli/releases/tag/v1.10.0):

> Fixed:
>
>- Ledger no longer creates a staking witness for staking key registration certificate (consistently with Trezor)
>- **superfluous witness output files are reported as a warning**, missing witness output files are reported as an error

I can sign the `tx.raw` with both `stake.hwsfile` AND `payment.hwsfile`, dropping either results in a problem.
Signing with only `stake.hwsfile`
```
Warning! A superfluous HW signing file specified (1 of 1), the witness was not created.
Warning! A superfluous output file specified (1 of 1), the file was not written to.
```
Signing with only `payment.hwsfile`
```
Error: Missing signing file for certificate
```

Signing with both works, but the current CNTools 10.2.3 also tries to create 2 separate output files per `--hw-signing-file` which is where the failure about not being written (**2 of 2** in the warnings/errors) comes from. After that the `transaction assemble` tries to use the missing second witness output, and that is where registration breaks down:

```
2023-04-28 21:22:34 UTC [ACTION] /home/guild/.local/bin/cardano-cli transaction assemble --tx-body-file /tmp/cnode/cntools/tx.raw --witness-file /tmp/cnode/cntools/tx.witness_BbqqQkA1cH --witness-file /tmp/cnode/cntools/tx.witness_QPCyPKlTNi --out-file /tmp/cnode/cntools/tx.signed_1682716954
2023-04-28 21:22:34 UTC [ERROR]  Command failed: transaction sign-witness  Error: Failed to decode neither the cli's serialisation format nor the ledger's CDDL serialisation format. TextEnvelope error: /tmp/cnode/cntools/tx.witness_QPCyPKlTNi: TextEnvelope aeson decode error: Error in $: not enough input
2023-04-28 21:22:34 UTC [ERROR]  TextEnvelopeCddl error: /tmp/cnode/cntools/tx.witness_QPCyPKlTNi: Could not JSON decode TextEnvelopeCddl file at: /tmp/cnode/cntools/tx.witness_QPCyPKlTNi Error: Error in $: not enough input
```

Taking the above and testing shows one less error when only 1 `--out-file` is used with both the stake and payment hwsfile's, but it still produces a superfluous warning. This seems unintuitive since this appears to be the correct usage.
```
$ $ cardano-hw-cli transaction witness --tx-file /tmp/cnode/cntools/tx.raw --hw-signing-file /opt/cardano/cnode/priv/wallet/TrezorWallet-extra2/stake.hwsfile --out-file /tmp/cnode/cntools/tx.witness_9yXrdLBKpl --testnet-magic 141 --hw-signing-file /opt/cardano/cnode/priv/wallet/TrezorWallet-extra2/payment.hwsfile 
Warning! A superfluous HW signing file specified (1 of 2), the witness was not created.
Writing to file '/tmp/cnode/cntools/tx.witness_9yXrdLBKpl'.
$ /home/guild/.local/bin/cardano-cli transaction assemble --tx-body-file /tmp/cnode/cntools/tx.raw --witness-file /tmp/cnode/cntools/tx.witness_9yXrdLBKpl --out-file /tmp/cnode/cntools/tx.signed_XXXXXXXXXX
$ cardano-cli transaction submit --tx-file /tmp/cnode/cntools/tx.signed_XXXXXXXXXX
```

I then tested deregistration since I submitted the registration manually, deregistration in the 10.2.3 cntools for HW wallets looks good:

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 >> WALLET >> DE-REGISTER
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Online mode  -  The default mode to use if all keys are available

Hybrid mode  -  1) Go through steps to build a transaction file
                2) Copy built tx file to offline computer
                3) Sign it using 'Sign Tx' with keys on offline computer
                   (CNTools started in offline mode '-o' without node connection)
                4) Copy the signed tx file back to online computer and submit using 'Submit Tx'

Selected value: [o] Online

# Select wallet to de-register (only registered wallets shown)
Selected wallet: VOS_ada (Funds: 97.998462 Ada)


INFO: follow directions on hardware device to witness the transaction
Writing to file '/tmp/cnode/cntools/tx.witness_hw2pfqOruh'.
Writing to file '/tmp/cnode/cntools/tx.witness_TquRBEiTIv'.
Transaction successfully submitted.

Waiting for new block to be created (timeout = 600 slots, 600s)
INFO: press any key to cancel and return (won't stop transaction)

VOS_ada successfully de-registered from chain!
Key deposit fee that will be refunded : 2.000000 Ada

press any key to proceed ..
```
Worked just fine. So  De Registering requires both the **stake.hwsfile** and the **payment.hwsfile** and does not print ANY superfluous messages when witnessing the transaction. This seems odd because doing the same exact thing for registering warns, why not now (rhetorical question, more for the cardano-hw-cli team).

I plan to do additional testing on the delegation, but I need to go back through and manually register the wallet again. I'll report back once I go through more multikey transactions, and keep my eyes open for a commit removing the second output file from the witness and input to the assemble.

**Comment by TrevorBenson** [comment]
I opened this ticket upstream w/ VacuumLabs, hopefully it helps clarify the correct steps and/or gets the warning removed entirely https://github.com/vacuumlabs/cardano-hw-cli/issues/163

**Comment by Scitz0** [comment]
[ceb621b](https://github.com/cardano-community/guild-operators/pull/1636/commits/ceb621b79e42c0ca4f13f48732204aea1ff8e262) should fix it so that all types now successfully can be witnessed. Though the warning on registration will still show, you can ignore this for now.

**Comment by TrevorBenson** [comment]
> [ceb621b](https://github.com/cardano-community/guild-operators/pull/1636/commits/ceb621b79e42c0ca4f13f48732204aea1ff8e262) should fix it so that all types now successfully can be witnessed. Though the warning on registration will still show, you can ignore this for now.

Confirmed, this looks like a winner. I went ahead and tested both a Ledger and Trezor to confirm `cardano-hw-cli` produced the expected behaviors.

# CNTools 10.2.3 
## Tested on guild (141) network 
### Device Trezor Model T
* De-Registered account manually registered.
* Registered same account.
* Delegated account to AHL

### Device Ledger Nano X
* Registered account
* Delegated account to AHL
* De-Registered account

-------
The warnings and errors are printed, but the basic transactions all work.

**Review by TrevorBenson — APPROVED** [review]
LGTM. I went through online and hybrid/offline registration with hardware wallets as well as more multisig pool creation. Each test case resulted in successful transactions submitted to the chain.

**Comment by TrevorBenson** [comment]
Leaving PR for @Scitz0 or @rdlrt to merge as the label is still set for **do-not-merge**.

Closes: #1635

**Pull request merged**
