### PR TITLE
Make TopoUpdater updates and variable extraction uniform with repo

### PR DESCRIPTION
**Pull request by rdlrt**

### CODE REVIEW

**Review by Scitz0 — APPROVED** [review]
👍

**Review by gufmar — APPROVED** [review]
LGTM - great integration

**Review by gufmar — APPROVED** [review]
LGTM

**Comment by gufmar** [comment]
There are two Updater-Service side changes that might be mentioned in the release notes.
The more important one: the fetch API endpoint now contains the IOG hydra default topology relay node for all invalid requests. (eg pending subscription, or temporary wrong blockNo) This makes the onboarding much easier and fail-safe.
As a second minor extension the returned topology list in addition to the distance on earth surface now also contains continent, country and region for every returned peer. This gives the SPO a better understanding of where its node is connected.

**Pull request merged**
