### PR TITLE
Update guild-deploy.sh with URL to download env configs

### PR DESCRIPTION
**Pull request by getwildr**
## Description
updated the env URL to download config files from IOG

## Where should the reviewer start?
fresh deploy on not guild net

## Motivation and context
current URL seemed broken

## Which issue it fixes?
nc

## How has this been tested?
deployed an instance on preview

### CODE REVIEW

**Review by Scitz0 — DISMISSED** [review]
👍

**Comment by Scitz0** [comment]
Any specific reason why change was requested?
Looking at it the existing url seem fine and point to the github repo holding the genesis / config files.

**Comment by getwildr** [comment]
Indeed. Apologies. Don't know what went wrong. Couldn't even find cardano-world repo on GitHub when I tried. Either too tired or a glitch there. Lets close this PR. Sorry.

**Comment by Scitz0** [comment]
No worries :) ... thanks for the effort.

**Pull request closed without merging**
