### PR TITLE
Update configs and node version support for 8.9.x

### PR DESCRIPTION
**Pull request by rdlrt**
## Description

- [x] Update topology formats
- [x] Update baseline node version references
- [x] Update node/cli dependency refs and pre-downloaded binaries
- [x] Update document references
- [x] Update dbsync version

### CODE REVIEW

**Review by Scitz0 — APPROVED** [review]
:+1:

**Comment by leonfs** [comment]
Is there an expected date of when this PR will be merged?

**Comment by Scitz0** [comment]
> Is there an expected date of when this PR will be merged? And thanks for the great work!

No date as of yet but you can always apply it by adding the running parameter `-b node-8.9.0` when executing the scripts.

**Comment by leonfs** [comment]
Thanks, @Scitz0. I tend to rely on the docker build, which I'm guessing it will be pushed once this gets merged. No worries though, I guess it can wait. 

Running on docker is tricky, even the Mithril scripts are focused on the host based deployment model. I'll see what docker based solution I might come up with and share it.

Anyway, thanks for the work.

**Comment by rdlrt** [comment]
@leonfs - Unfortunately, we cannot go ahead with merging this until we have a proper compatibility matrix between different components (currently, node and CLI teams work closely and seem to be part of release, while other components are left as external with a very vague situation). Hence, our guild-ops official support stays at 8.7.3 🙂

**Review by TrevorBenson — APPROVED** [review]

**Pull request merged**
